// <auto-generated />
namespace DataService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NewDb20160404 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewDb20160404));
        
        string IMigrationMetadata.Id
        {
            get { return "201604042023267_NewDb20160404"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
