// <auto-generated />
namespace DataService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NewDbSecond20160406 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewDbSecond20160406));
        
        string IMigrationMetadata.Id
        {
            get { return "201604061603396_NewDbSecond20160406"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
